version: "3"

services:  
  # postgresdb:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password123

  node-openai-api:
    image: joebanhong/node-opeanai-stream-api:latest
    restart: always
    ports:
      - "3999:3000"
    environment:
      OPENAI_API_KEY: "xxx"
      PORT: 3000
